#pragma once

enum RESOURCETYPE { RESOURCE_LOGO , RESOURCE_LOGIN , RESOURCE_LOBBY , RESOURCE_LOADING , RESOURCE_STAGE , RESOURCE_GESTALT, RESOURCE_STATIC, RESOURCE_END };

//## 옵저버 메시지 ID
enum eMSGID {
	MSG_TERRAIN, MSG_CUBEPAIR, MSG_ADDCUBE, MSG_DELETECUBE,
	MSG_INFOLIST, MSG_PLAYERINFO, MSG_CAMERADIST,
	MSG_INVEN, MSG_INVENITEM, MSG_SLOTNUM,
	MSG_PLAYERHP,
	MSG_END
};

enum eMapType
{
	MAP_GESTALT,
	MAP_CONVOY,
	MAP_END,
};

enum CHARSTATE
{
	CHARSTATE_ALIVE,
	CHARSTATE_DEAD,
};

enum CAMERAMODE
{
	CAMERA_FPS,
	CAMERA_STATIC,
	CAMERA_DYNAMIC,
	CAMERA_END,
};

enum HITTARGET
{
	HIT_CHARACTER,
	HIT_STRUCTURE,
	HIT_SHOCKCORE,
	HIT_NONE,
};


enum WEAPONTYPE
{
	WEAPON_ASSULTRIFLE,
	WEAPON_FLAKCANNON,
	WEAPON_END,
};
