#pragma once

enum RESOURCETYPE { RESOURCE_LOGO, RESOURCE_SELECT, RESOURCE_QUEST, RESOURCE_STAGE, RESOURCE_STATIC, RESOURCE_END };

//## 옵저버 메시지 ID
enum eMSGID {
	MSG_TERRAIN, MSG_CUBEPAIR, MSG_ADDCUBE, MSG_DELETECUBE,
	MSG_INFOLIST, MSG_PLAYERINFO, MSG_CAMERADIST,
	MSG_INVEN, MSG_INVENITEM, MSG_SLOTNUM,
	MSG_PLAYERHP,
	MSG_END
};

enum ePlayerState
{
	STATE_STAND = 0,
	STATE_CATCH,
	STATE_WALK,
	STATE_ATT,
	STATE_HIT,
	STATE_DEFENSE,
	STATE_DEAD,
	STATE_END
};
